### ISSUE TITLE
Describe testing and setup in README

### ISSUE THREAD

**Issue by niccokunzmann** [mergecal/python-mergecal#10]
### Describe the bug

It should be easy to setup the codebase

Describe how to setup the
- development environment
- the dependencies
- code style checks if there are any
- run the tests

### To Reproduce

Read the README and setup.

### Version

1

### Platform

any

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by abe-101** [comment]
So the Template we used generate a contributing guide as part of the docs
https://mergecal.readthedocs.io/en/latest/contributing.html
I prefer to have one source of truth so should we simply add a link in the readme to that page?

**Comment by niccokunzmann** [comment]
No, this is perfect! I did not see that this is already on readthedocs!
