### ISSUE TITLE
main branch is failing

### ISSUE THREAD

**Issue by niccokunzmann** [mergecal/python-mergecal#11]
### Describe the bug

I reported the bug here:

https://github.com/python-semantic-release/python-semantic-release/issues/1019

The release is failing.

### To Reproduce

Create a new commit on `main`.
https://github.com/mergecal/python-mergecal/actions/runs/10734987801/job/29771424749
https://github.com/mergecal/python-mergecal/commit/ce7b73c50785a9d3ac8fca8a627420e58ad389ac

### Version

main

### Platform

github ci

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by niccokunzmann** [comment]
Uhh. It seems we are also linting .md files ... I will get to that!

**Comment by niccokunzmann** [comment]
To close this:

- [ ] remove the error in the main build
- [ ] notify the issue https://github.com/python-semantic-release/python-semantic-release/issues/1019
- [ ] consider to open an issue in the template with the fix

**Comment by abe-101** [comment]
can this be closed?
the fix is implemented here: https://github.com/mergecal/python-mergecal/commit/05b32df73344fea188feb36eb4abe6981895ccd4
and the template has also been fixed
https://github.com/browniebroke/pypackage-template/pull/797

**Comment by niccokunzmann** [comment]
yes, that can be closed and I notify the issue
