### ISSUE TITLE
Remove --calscale

### ISSUE THREAD

**Issue by niccokunzmann** [mergecal/python-mergecal#15]
The calscale can only be GREGORIAN it does not make sense to set this.
I think, this should be removed. I do not know of any standard that changes that but if you have another one supported that does that, please let me know. Even the HEBREW scale for recurrences works within the GREGORIAN calendar scale. Is there any?

> Description:  This memo is based on the Gregorian calendar scale.
      The Gregorian calendar scale is assumed if this property is not
      specified in the iCalendar object.

**Comment by abe-101** [comment]
ok - we can remove it
