### ISSUE TITLE
Settings access - niccokunzmann

### ISSUE THREAD

**Issue by niccokunzmann** [mergecal/python-mergecal#9]
### Describe the bug

Hi, I would like to have full access to the settings. I wonder if this is possible. I might need to be a maintainer. Right now, I cannot configure much.
What I wanted to do is to
- auto-delete merged branches.
- allow empty Issue templates

### To Reproduce

click on settings

### Version

1

### Platform

Ubuntu

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by abe-101** [comment]
I made you an admin
